{
 "title": "Commit History",
 "tags": [ "commit-history" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo",
    "label": "repo",
    "query": "select fullname as __text, id as __value from repo where disabled=false"
   },
   {
    "name": "app",
    "query": "select name as __text, id as __value from tag where disabled=false and jhi_type='app'"
   }
  ]
 },
 "panels": [
  {
   "title": "Commit History - App",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select metric, value::int, (current_timestamp + metric::int * interval '1 seconds') as time from (\nselect entity, jsonb_array_elements(data)->>'week' as metric, (jsonb_array_elements(data)->>'count')::int as value, doc\nfrom source_commits('tag', 'by-week',  'git-tag') order by metric) as _\nwhere (entity->>'id')::int=$app;"
    }
   ]
  },
  {
   "title": "Commit History - Repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select metric, value::int, (current_timestamp + metric::int * interval '1 seconds') as time from (\nselect entity, jsonb_array_elements(data)->>'week' as metric, (jsonb_array_elements(data)->>'count')::int as value, doc\nfrom source_commits('repo', 'by-week',  'git-repo') order by metric) as _\nwhere (entity->>'id')::int=$repo;"
    }
   ]
  },
  {
   "title": "Commit History - Org",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select metric, value::int, (current_timestamp + metric::int * interval '1 seconds') as time from (\nselect entity, jsonb_array_elements(data)->>'week' as metric, (jsonb_array_elements(data)->>'count')::int as value, doc\nfrom source_commits('org', 'by-week',  'git-org') order by metric) as _;"
    }
   ]
  },
  {
   "title": "Commit History - Scm",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select metric, value::int, (current_timestamp + metric::int * interval '1 seconds') as time from (\nselect entity, jsonb_array_elements(data)->>'week' as metric, (jsonb_array_elements(data)->>'count')::int as value, doc\nfrom source_commits('scm', 'by-week',  'git-scm') order by metric) as _;"
    }
   ]
  },
  {
   "title": "Commit History - All",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select metric, value::int, (current_timestamp + metric::int * interval '1 seconds') as time from (\nselect entity, jsonb_array_elements(data)->>'week' as metric, (jsonb_array_elements(data)->>'count')::int as value, doc\nfrom source_commits('all', 'by-week',  'git-all') order by metric) as _;"
    }
   ]
  }
 ]
}