{
 "title": "The Dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total repos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select (doc->>'totalrepos') from local_analysis where doc->>'subtype'='git-global';"
    }
   ]
  },
  { "title": "Languages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Top Languages",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  metric AS metric,\n  value\nFROM source_top_languages\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Top Languages",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "select metric as language, value as \"repo count\" from source_top_languages;"
    }
   ]
  },
  { "title": "Lines of Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "By Lines of Code",
   "type": "table",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select 'There are '|| totallines::text ||' LOC'||'   ',\n 'There are ' || (mostusedlanguage->>'lines') ||' lines '|| (mostusedlanguage->>'name') || ' LOC',\n  (largestrepo->>'name') || ' is the biggest ' || (largestrepo->>'loc') || ' LOC'\n from source_loc;\n"
    }
   ]
  },
  {
   "title": "Top Projects (by Lines of Code)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  metric AS metric,\n  value\nFROM source_loc_per_project\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Totals",
   "type": "table",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "select \n\t'There were '||(activity->>'activedevs')||' developers commiting code' as total_devs,\n\t(activity->>'totalcommits')||' commits to '||(activity->>'activerepos')||' repositories' as total_commits\nfrom source_activity('alltime', 'git-global');\n"
    }
   ]
  },
  {
   "title": "Top 5 Repos",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "select \n\tjsonb_array_elements(activity->'toprepos')->>'name' as name,\n\t(jsonb_array_elements(activity->'toprepos')->>'commits')::int as commits\nfrom source_activity('alltime', 'git-global')\norder by commits desc limit 5;"
    }
   ]
  },
  {
   "title": "Top 5 Contributors",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 30 },
   "targets": [
    {
     "rawSql": "select \n\tjsonb_array_elements(activity->'topcommitters')->>'name' as name,\n\t(jsonb_array_elements(activity->'topcommitters')->>'commits')::int as commits\nfrom source_activity('lastyear', 'git-global')\norder by commits desc limit 5;"
    }
   ]
  },
  {
   "title": "Commit History - All",
   "type": "graph",
   "description": "Commits per week.\nUse the link below to drill down:",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select metric, value::int, (current_timestamp + metric::int * interval '1 seconds') as time from (\nselect entity, jsonb_array_elements(data)->>'week' as metric, (jsonb_array_elements(data)->>'count')::int as value, doc\nfrom source_commits('all', 'by-week',  'git-all') order by metric) as _;"
    }
   ]
  },
  { "title": "Activity by Time", "type": "dashlist", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 } }
 ]
}