{
 "title": "Code Sizings",
 "tags": [ "sizings" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Code Sizings - Org",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select entity->>'name' as name, small, medium, large \nfrom (select entity, data->0->'value' as small, data->1->'value' as medium, data->2->'value' as large, doc \nfrom source_sizings('org', 'git-org')) as _\norder by name;"
    }
   ]
  },
  {
   "title": "Code Sizings - App",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select entity->>'name' as name, small, medium, large \nfrom (select entity, data->0->'value' as small, data->1->'value' as medium, data->2->'value' as large, doc \nfrom source_sizings('tag', 'git-tag')) as _\norder by name;"
    }
   ]
  },
  {
   "title": "Code Sizings - Repo",
   "type": "table",
   "gridPos": { "h": 24, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select entity->>'fullname' as name, small, medium, large \nfrom (select entity, data->0->'value' as small, data->1->'value' as medium, data->2->'value' as large, doc \nfrom source_sizings('repo', 'git-repo')) as _\norder by name;"
    }
   ]
  }
 ]
}