{
 "title": "Activity - Last Week",
 "tags": [ "activity" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Totals",
   "type": "table",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n\t'There were '||(activity->>'activedevs')||' developers commiting code' as total_devs,\n\t(activity->>'totalcommits')||' commits to '||(activity->>'activerepos')||' repositories' as total_commits\nfrom source_activity('lastweek', 'git-global');\n"
    }
   ]
  },
  {
   "title": "Being Scanned by Veracode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "rawSql": "select '100%';\n" }
   ]
  },
  {
   "title": "Top 5 Repos",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select \n\tjsonb_array_elements(activity->'toprepos')->>'name' as name,\n\t(jsonb_array_elements(activity->'toprepos')->>'commits')::int as commits\nfrom source_activity('lastweek', 'git-global')\norder by commits desc limit 5;"
    }
   ]
  },
  {
   "title": "Top 5 Contributors",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 3 },
   "targets": [
    {
     "rawSql": "select \n\tjsonb_array_elements(activity->'topcommitters')->>'name' as name,\n\t(jsonb_array_elements(activity->'topcommitters')->>'commits')::int as commits\nfrom source_activity('lastweek', 'git-global')\norder by commits desc limit 5;"
    }
   ]
  }
 ]
}